[server]
headless = true
address = "0.0.0.0"
port = 5000
enableXsrfProtection = false
enableCORS = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
base = "dark"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
magicEnabled = true
installTracer = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[global]
developmentMode = false
