[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1F25"
textColor = "#FAFAFA"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false
